### ISSUE TITLE
Course no longer available on Coursera

### ISSUE THREAD

**Issue by Blargian** [breadrock1/CourseraWhiteBeltC#1]
Unfortunately the [course](https://www.coursera.org/learn/c-plus-plus-white) seems to no longer be available at Coursera due to the evident shortsightedness of the company given the current geopolitical situation. 

Is it possible that this course is available for access somewhere else?

**Comment by breadrock1** [comment]
Hi, @Blargian. I haven't followed the course for a long time. Really don't know any sources with available current course. The authors are [MIPT University](https://mipt.ru/) and [Yandex](https://practicum.yandex.ru/cpp/), maybe on these site you can find any information?!  

If i find something, i'll share with you 😄
